# Base

# site
title: 慢慢炖
description: 股票不是拿来炒的，是要慢慢炖的。

# url
# url of website. format like http://<domain>/<path> or https://<domain>
url: https://lowkey2016.github.io/

# theme
# default is ccc45
theme: donob

# pagination
# post count per page. set 0 to disable it
# default is 10
per_page: 10

# menu
# navigation menus of website
menu:
  所有文章: /posts/
  分类: /tags/
  关于: /about/

# default category name
# default is "uncategorized"
default_category: 未分类

# content
# GitHub user/repository
# website contents comes from this repository issues
user: lowkey2016
repository: lowkey2016.github.io


# Advance

# scripts
# script file names
scripts:
  - content.js
  # - active.js

# plugins
# npm modules
plugins:
  - acyort-rss
  - acyort-archives
  - acyort-paginator

rss: rss.xml

# archives:
#   per_page: 5

# output
# where static site files located
public_dir: /

# authors
# Github usernames, users whose issues can be generated to post
authors:
  - lowkey2016

# timezone
# website timezone. use machine setting by default
# example: "America/New_York", "Japan", "UTC", or "Asia/Shanghai"
timezone: Asia/Guangzhou

# language
# language of website, theme support is needed
# default is default
language: cn

# code line numbers
# whether showing line numbers in code block
# default is true
# line_numbers:

# order
# post ordering, order posts by issues create_time(created) or update_time(updated)
# default is created
# order:

# directory
# subdirectory in public_dir
# default is categories, tags, posts
category_dir: categories
tag_dir: tags
post_dir: posts

# token
# github access token
# In order to prevent the token from removed by github, you should add a # inside it
# for example the original token abcdedf should be replaced with a#bcdef.
token:

# cache
# whether caching GitHub issues data, just for development
# default false
cache:

# Other
# customize some settings if necessary

# disqus:
# favicon:
